name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  tests:
    strategy:
      fail-fast: true
    name: forge tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
  solhint:
    name: solhint linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install solhint
        run: |
          npm install -g solhint
      - name: Run solhint
        run: |
          solhint 'src/**/*.sol'
  slither:
    name: slither scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install solc-select
        run: |
          pip3 install solc-select
      - name: Install solc 0.8.7
        run: |
          solc-select install 0.8.7
      - name: Use solc 0.8.7
        run: |
          solc-select use 0.8.7
      - name: Install slither
        run: |
          pip install slither-analyzer
      - name: Run slither
        run: |
          slither .
