name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: solhint
        uses: contractshark/inject-solhint-ci@latest
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          solhint_input: 'src/**/*.sol'
